server:
  port: 9281

spring.application:
  name: runners


spring.datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: password

spring.h2.console:
  enabled: true

spring.jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
